version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:8.0
    container_name: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: refrigerator_observer
    ports: ["3306:3306"]
